"""Unit tests for the Issue Formatter module."""

import pytest
from core.issue_formatter import (
    IssueFormatter,
    preview_issue,
    ISSUE_TEMPLATES
)
from core.webbuilder_models import (
    GitHubIssue,
    IssuePreviewRequest,
    WorkflowSuggestion
)


class TestIssueFormatter:
    """Test suite for IssueFormatter class."""

    @pytest.fixture
    def formatter(self):
        """Create IssueFormatter instance."""
        return IssueFormatter()

    @pytest.fixture
    def sample_issue(self):
        """Create a sample GitHubIssue for testing."""
        return GitHubIssue(
            title="Add user authentication",
            body="""## Description
Implement user authentication system

## Requirements
- Login functionality
- Registration flow
- Password reset

## Technical Approach
Use JWT tokens for session management""",
            labels=["feature", "authentication", "webbuilder"],
            classification="feature",
            workflow="adw_plan_build_test_iso",
            model_set="base"
        )

    def test_format_issue_feature(self, formatter, sample_issue):
        """Test formatting a feature issue."""
        formatted = formatter.format_issue(sample_issue)

        # Check that key sections are present
        assert "# Add user authentication" in formatted
        assert "## Description" in formatted
        assert "## Requirements" in formatted
        assert "- Login functionality" in formatted
        assert "## Technical Approach" in formatted
        assert "## Workflow" in formatted
        assert "adw_plan_build_test_iso model_set base" in formatted
        assert "## Labels" in formatted
        assert "Generated by TAC WebBuilder" in formatted

    def test_format_issue_bug(self, formatter):
        """Test formatting a bug issue."""
        bug_issue = GitHubIssue(
            title="Fix login error",
            body="""## Description
Login fails with 500 error

## Steps to Reproduce
1. Go to login page
2. Enter credentials
3. Click submit

## Expected Behavior
User should be logged in

## Actual Behavior
500 error displayed""",
            labels=["bug", "urgent"],
            classification="bug",
            workflow="adw_plan_build_test_iso",
            model_set="base"
        )

        formatted = formatter.format_issue(bug_issue)

        assert "# Fix login error" in formatted
        assert "## Issue Description" in formatted
        assert "## Steps to Reproduce" in formatted
        assert "## Expected vs Actual Behavior" in formatted
        assert "adw_plan_build_test_iso model_set base" in formatted

    def test_format_issue_chore(self, formatter):
        """Test formatting a chore issue."""
        chore_issue = GitHubIssue(
            title="Update dependencies",
            body="""## Description
Update all npm packages

## Tasks
- Update React to v18
- Update TypeScript to v5
- Test for breaking changes""",
            labels=["chore", "dependencies"],
            classification="chore",
            workflow="adw_simple_iso",
            model_set="base"
        )

        formatted = formatter.format_issue(chore_issue)

        assert "# Update dependencies" in formatted
        assert "## Tasks" in formatted
        assert "adw_simple_iso model_set base" in formatted

    def test_parse_issue_body(self, formatter):
        """Test parsing issue body into sections."""
        body = """Initial description text

## Requirements
- Requirement 1
- Requirement 2

## Technical Approach
Use modern patterns

## Another Section
Additional content"""

        sections = formatter._parse_issue_body(body)

        assert sections["description"] == "Initial description text\n"
        assert sections["requirements"] == ["Requirement 1", "Requirement 2"]
        assert sections["technical_approach"] == "Use modern patterns"
        assert sections["another_section"] == "Additional content"

    def test_format_requirements(self, formatter):
        """Test formatting requirements list."""
        # Test with requirements
        requirements = ["Login feature", "User registration", "Password reset"]
        formatted = formatter._format_requirements(requirements)

        assert "- Login feature" in formatted
        assert "- User registration" in formatted
        assert "- Password reset" in formatted

        # Test with empty requirements
        formatted = formatter._format_requirements([])
        assert "- No specific requirements identified" in formatted

        # Test with requirements already having dashes
        requirements = ["- Already formatted", "Not formatted"]
        formatted = formatter._format_requirements(requirements)
        assert "- Already formatted" in formatted
        assert "- Not formatted" in formatted

    def test_suggest_adw_workflow_bug(self, formatter):
        """Test workflow suggestion for bugs."""
        suggestion = formatter.suggest_adw_workflow("medium", "bug", 3)

        assert suggestion.workflow_name == "adw_plan_build_test_iso"
        assert suggestion.model_set == "base"
        assert "Bug fixes require" in suggestion.reasoning

    def test_suggest_adw_workflow_high_complexity(self, formatter):
        """Test workflow suggestion for high complexity."""
        suggestion = formatter.suggest_adw_workflow("high", "feature", 6)

        assert suggestion.workflow_name == "adw_sdlc_iso"
        assert suggestion.model_set == "heavy"
        assert "Complex implementation" in suggestion.reasoning

    def test_suggest_adw_workflow_medium_complexity(self, formatter):
        """Test workflow suggestion for medium complexity."""
        suggestion = formatter.suggest_adw_workflow("medium", "feature", 3)

        assert suggestion.workflow_name == "adw_plan_build_test_iso"
        assert suggestion.model_set == "base"
        assert "Moderate complexity" in suggestion.reasoning

    def test_suggest_adw_workflow_low_complexity(self, formatter):
        """Test workflow suggestion for low complexity."""
        suggestion = formatter.suggest_adw_workflow("low", "feature", 1)

        assert suggestion.workflow_name == "adw_simple_iso"
        assert suggestion.model_set == "base"
        assert "Simple task" in suggestion.reasoning

    def test_format_preview_terminal(self, formatter, sample_issue):
        """Test terminal preview formatting."""
        preview = formatter.format_preview(sample_issue, "terminal")

        # Terminal preview should contain key information
        assert "GitHub Issue Preview" in preview
        assert "Add user authentication" in preview
        assert "feature" in preview
        assert "adw_plan_build_test_iso" in preview

    def test_format_preview_markdown(self, formatter, sample_issue):
        """Test markdown preview formatting."""
        preview = formatter.format_preview(sample_issue, "markdown")

        # Should return the full formatted issue
        assert "# Add user authentication" in preview
        assert "## Description" in preview

    def test_format_preview_html(self, formatter, sample_issue):
        """Test HTML preview formatting."""
        preview = formatter.format_preview(sample_issue, "html")

        # HTML preview should contain HTML tags
        assert '<div class="issue-preview">' in preview
        assert '<h2>Add user authentication</h2>' in preview
        assert '<span class="issue-type">feature</span>' in preview

    def test_create_steps_to_reproduce(self, formatter):
        """Test creating steps to reproduce for bug reports."""
        steps = formatter.create_steps_to_reproduce("Login button not working")

        assert "1. [Describe the initial state/setup]" in steps
        assert "2. [Describe the action taken]" in steps
        assert "3. [Describe what happened]" in steps
        assert "4. [Describe any error messages" in steps

    def test_create_acceptance_criteria(self, formatter):
        """Test creating acceptance criteria from requirements."""
        # Test with requirements
        requirements = ["User can login", "Password is encrypted", "Session expires after 24h"]
        criteria = formatter.create_acceptance_criteria(requirements)

        assert "- [ ] User can login" in criteria
        assert "- [ ] Password is encrypted" in criteria
        assert "- [ ] Session expires after 24h" in criteria
        assert "- [ ] Unit tests written and passing" in criteria
        assert "- [ ] Documentation updated" in criteria

        # Test with empty requirements
        criteria = formatter.create_acceptance_criteria([])
        assert "- [ ] Implementation complete" in criteria
        assert "- [ ] Tests pass" in criteria

    def test_preview_issue_function(self):
        """Test the preview_issue function."""
        issue = GitHubIssue(
            title="Test Issue",
            body="Test body content",
            labels=["test"],
            classification="feature",
            workflow="adw_sdlc_iso",
            model_set="heavy"
        )

        request = IssuePreviewRequest(
            issue=issue,
            format="terminal"
        )

        response = preview_issue(request)

        assert response.formatted_preview
        assert response.estimated_complexity == "High - Full SDLC required"
        assert response.suggested_timeline == "3-5 days"

    def test_preview_issue_simple_workflow(self):
        """Test preview with simple workflow."""
        issue = GitHubIssue(
            title="Simple Task",
            body="Quick fix",
            labels=["minor"],
            classification="chore",
            workflow="adw_simple_iso",
            model_set="base"
        )

        request = IssuePreviewRequest(
            issue=issue,
            format="markdown"
        )

        response = preview_issue(request)

        assert response.estimated_complexity == "Low - Simple implementation"
        assert response.suggested_timeline == "< 1 day"

    def test_custom_template_override(self, formatter):
        """Test using a custom template."""
        custom_template = """# Custom: {title}
Body: {description}
Workflow: {adw_workflow}"""

        issue = GitHubIssue(
            title="Test Title",
            body="## Description\nTest description",
            labels=["test"],
            classification="feature",
            workflow="test_workflow",
            model_set="base"
        )

        formatted = formatter.format_issue(issue, custom_template)

        assert "# Custom: Test Title" in formatted
        assert "Body: Test description" in formatted
        assert "Workflow: test_workflow" in formatted